config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root             'static_pages#home'
  get 'add'        => 'products#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'cart'       => 'products#cart'
  resources :users
  resources :products
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, presence: true
  validates :image_url, presence: true
  validates :description, presence: true
  validates :price, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :name, presence: true,  length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  # GET /products
  def index
    if !logged_in?
      redirect_to root_url
    end
    @products = Product.all
  end

  # GET /products/new || /add
  def new
    @product = Product.new
  end

  # POST /products
  def create
    @product = Product.new(product_params)    # Not the final implementation!
    if @product.save
      redirect_to products_url
      flash[:success] = "Item Added successfully"
    else
      render 'new'
    end
  end

  private
  # Never trust parameters from the scary internet, only allow the white list through.
  def product_params
    params.require(:product).permit(:name, :description, :image_url, :price)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    if logged_in?
      redirect_to root_url
    end
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # Log the user in and redirect to the user's show page.
      log_in user
      redirect_to products_url
    else
      flash[:danger] = 'Invalid email/password combination' # Not quite right!
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      if is_agent?
        redirect_to add_url
      else
        redirect_to products_url
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
 def full_title(page_title = '')
   base_title = "Ruby on Rails Tutorial Sample App"
   if page_title.empty?
     base_title
   else
     page_title + " | " + base_title
   end
 end
end

app/helpers/products_helper.rb
# frozen_string_literal: true

module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Returns true if the user is an agent to add products
  def is_agent?
    !current_user.nil? && current_user.role === "agent"
  end

  # Logs out the current user.
   def log_out
     session.delete(:user_id)
     @current_user = nil
   end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "food app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>

          <% if is_agent? %>
            <li><%= link_to "Products",   products_url %></li>
            <li>  <%= link_to "Add Product", add_path %>   </li>
          <% else %>
            <li><%= link_to "Home",   root_path %></li>
          <% end %>
          <li>
            <%= link_to "Log out", logout_path, method: "delete" %>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "application" %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>

    </div>
</body>
</html>

<!--
<%= debug(params) if Rails.env.development? %>
User.create(name: "manikanta k", email: "manikanta2@example.com", password: "1234abcd", password_confirmation: "1234abcd", role: "agent")
User.create(name: "chitti k", email: "chitti2@example.com", password: "1234abcdef", password_confirmation: "1234abcdef", role: "user")

User.create(name: "manikanta k", email: "test1@example.com", password: "test123", password_confirmation: "test123", role: "agent")
User.create(name: "Chitti k", email: "test2@example.com", password: "test123", password_confirmation: "test123", role: "user")
-->

app/views/products/cart.html.erb
<h1>Checkout Cart</h1>

<div class="products-container">
  <div class="items-container">
  </div>
</div>

<script type="text/javascript">
  cartDetails = JSON.parse(localStorage.getItem(CHECKOUT_CART_PATH));
  let total = 0
  for (item of cartDetails) {
    const {name, price, image_url} = item
    total += Number(price)
    $('.items-container').append(
      `
        <div class="item">
          <img src="${image_url}" width="244" height='160' />
          <div class="heading">${name}</div>
          <span class="price">Rs. ${price}</div>
        </div>
      `
    )
  }
  if (total) {
    $('.products-container').append(
      `
      <hr >
        <div class="flex-end">
          <div class="price">
            Total: ${total}
          </div>
          <br />
          <button class="btn btn-lg btn-success buy-now" >Buy Now</button>
      </div>
    `
    )
  }

</script>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Recommended</h1>

<a href="/cart">
  <button class="btn btn-lg btn-warning pull-right">Checkout</button>
</a>

<div class="products-container">
  <div class="totals">
    <%= @products.length %> ITEMS
  </div>
  <div class="items-container">
    <% @products.each do |product| %>
      <div class="item">
        <%= image_tag(product.image_url, width: "244", height: '160') %>
        <div>
          <div class="heading"><%= product.name %></div>
          <div class="description"><%= product.description %></div>
          <div>Rs. <%= product.price %></div>
        </div>
        <% if !is_agent? %>
        <%= content_tag :button, class: "btn btn-lg btn-primary cart-button", data: {product: product} do %>
        Add to cart
        <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

<%= link_to('cart') do %>
  <button class="btn btn-lg btn-warning pull-right">Checkout</button>
<% end %>

app/views/products/new.html.erb
<% provide(:title, 'Add Products') %>

<%# If any form errors then it will be displayed %>
<% if @product.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@product.errors.count, "error") %> prohibited this from being saved:</h2>

    <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<% if is_agent? %>
  <h1>Add Product</h1>

  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(@product) do |f| %>
        <%= f.label :name %>
        <%= f.text_field :name %>

        <%= f.label :image_url %>
        <%= f.text_field :image_url %>

        <%= f.label :description %>
        <%= f.text_field :description %>

        <%= f.label :price %>
        <%= f.text_field :price %>

        <%= f.submit "Add new product", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
<% else %>
  <h1>Access forbidden</h1>
  <p>Only agent can add products</p>
<% end %>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to the Food App</h1>

  <h2>
    This is the home page for the
    Here you can see list of avaialable food items and you can order them
  </h2>

  <%= link_to "Login now!", login_path, class: "btn btn-lg btn-primary" %>
</div>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<%= @user.name %>, <%= @user.email %>